; Waveshare ESP32-C6-ePaper-1.54 — Rock Paper Scissors
[env:esp32-c6-epaper]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.embed_files =
  assets/sfx_win.pcm
  assets/sfx_lose.pcm
  assets/sfx_draw.pcm
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DCORE_DEBUG_LEVEL=1
  -I src/esp_codec_dev/include
  -I src/esp_codec_dev/interface
  -I src/esp_codec_dev/device/include
  -I src/esp_codec_dev
  -I src/codec_board
lib_ldf_mode = deep+
build_src_filter =
  +<*>
  -<codec_board/lcd_init.c>
  -<codec_board/drv/>
